description: > # this means to ignore newlines until "baseurl:"
  My personaly thoughts and opinions on all things technology and life. 
theme: jekyll-theme-midnight
permalink: /:categories/:year/:month/:day/:title
